apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: khouloud123456/movies_client:first
        ports:
        - containerPort: 3000
        env:
          - name: DANGEROUSLY_DISABLE_HOST_CHECK
            value: 'true'
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: client
  #type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      #nodePort: 30000
