apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: khouloud123456/movies_server:first
        ports:
        - containerPort: 3001
        
---
apiVersion: v1
kind: Service
metadata:
  labels : 
    app: server
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
