apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: server
        image: mongo:latest
        ports:
        - containerPort: 27017
        
---
apiVersion: v1
kind: Service
metadata:
  labels : 
    app: database
  name: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
